CREATE TABLE ru_en_yandex (
	_from TEXT NOT NULL PRIMARY KEY,
	_to TEXT NOT NULL
);

CREATE TABLE en_ru_yandex (
	_from TEXT NOT NULL PRIMARY KEY,
	_to TEXT NOT NULL
);

CREATE TABLE ru_en_google (
	_from TEXT NOT NULL PRIMARY KEY,
	_to TEXT NOT NULL
);

CREATE TABLE en_ru_google (
	_from TEXT NOT NULL PRIMARY KEY,
	_to TEXT NOT NULL
);

CREATE TABLE ru_en_itranslate4 (
	_from TEXT NOT NULL PRIMARY KEY,
	_to TEXT NOT NULL
);

CREATE TABLE en_ru_itranslate4 (
	_from TEXT NOT NULL PRIMARY KEY,
	_to TEXT NOT NULL
);
